// GENERATED by scripts/generate-catalogue.mjs — do not hand-edit.
// Contains PUBLIC keys only, derived from ~/agent-vault/keys/*.json. No
// private key material is present in this file or was logged while
// generating it.

export type Merchant = {
  label: string;
  /** The merchant's own wallet address (not their Demo USD token account). */
  wallet: string;
};

/** Bank-published merchant catalogue. Fixed list of 4 — matches the
 * program's MAX_MERCHANTS_PER_AGENT. */
export const MERCHANT_CATALOGUE: Merchant[] = [
  {
    "label": "Noonly",
    "wallet": "DFTuEQUPL2X3ZPnKd649r5iE4Dtfg9anXKRwVW7Qc3ne"
  },
  {
    "label": "Talabird",
    "wallet": "79SqU4CSRmu6bq7QQiFet8bHLs7zJj8e4yWiTZF4F5zo"
  },
  {
    "label": "Zomatic",
    "wallet": "4TBdAhTAKeYCSKYnc5vtrAgMDkgrHT9AoJfEmxKc8vqK"
  },
  {
    "label": "Kuber Eats",
    "wallet": "2wqyxRpzQApHzdsNSz1d8HQpJD3JkhtYsZ8MVpiGE9fD"
  }
];

/** The "Demo USD" test token created in M5. Decimals: 0. */
export const DEMO_USD_MINT = '3txU6ZAzx6oAMhFMd9CjuRTFB9YkCYvnYSZeFfLK19ec';
